### ISSUE TITLE
Breaks with Avalonia v11.0.6

### ISSUE THREAD

**Issue by holotrek** [ArchLeaders/Avalonia.MenuFactory#1]
Error is:
```
System.MissingMethodException: 'Method not found: 'Void Avalonia.Controls.ItemsControl.set_Items(System.Collections.IEnumerable)'.'
```

It appears that the Items property used to be settable but is no longer. The error appears to occur on this line: https://github.com/ArchLeaders/Avalonia.MenuFactory/blob/master/Avalonia.MenuFactory/MenuFactory.cs#L92

**Comment by ArchLeaders** [comment]
Should be fixed in 4b5ec3daac03e2403561a8085e9ce3aa043afb29
